FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir kafka-python

COPY producer/consumer.py /app/consumer.py

ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092 \
    KAFKA_TOPIC=creditcard-transactions \
    GROUP_ID=creditcard-consumer

CMD ["python", "producer/consumer.py"]