FROM python:3.10-slim

# Không tạo .pyc + log thẳng ra stdout
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy requirements trước để cache layer
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Code sẽ được mount bằng volume (dev)
# hoặc COPY sau (prod)
